version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.6.4
      - image: trufflesuite/ganache-cli:v6.4.1
        command: -d -k=petersburg -i 1001
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo pip install -r requirements.txt
      - run:
          name: Lint
          command: flake8
      - run:
          name: Test
          command: tox
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
