version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: sudo pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/build
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build
  test:
    working_directory: ~/build
    docker:
      - image: circleci/python:3.6.4
    steps:
      - restore_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Dependencies
          command: sudo pip install -r requirements.txt
      - run:
          name: Test
          command: tox

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
